name: daily data run
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1-5"
jobs:
  deploy_source:
    name: daily data run
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v1
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.ACCESS_KEY }}
          aws_secret_access_key: ${{ secrets.SECRET_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: daily-data-run
          source: jobs/generate_data.py