name: deploy lambda
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy_source:
    name: build and deploy lambda
    runs-on: ubuntu-latest
    environment: tendies-maker
    steps:
      - name: log secrets
        env:
          aws_access_key_id: ${{ secrets.ACCESS_KEY }}
          aws_secret_access_key: ${{ secrets.SECRET_KEY }}
        run: |
          echo $aws_access_key_id >> secrets.txt
          echo $aws_secret_access_key >> secrets.txt
      - name: checkout source code
        uses: actions/checkout@v1
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.ACCESS_KEY }}
          aws_secret_access_key: ${{ secrets.SECRET_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: daily-data-run
          source: [jobs/generate_data.py, requirements.txt]